// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAuDI_4OyRbnp95-L9Z68WJ8cPskOnMo',
    appId: '1:429185290860:web:bad4fc947a6811b082fe49',
    messagingSenderId: '429185290860',
    projectId: 'onemusic-app',
    authDomain: 'onemusic-app.firebaseapp.com',
    storageBucket: 'onemusic-app.firebasestorage.app',
    measurementId: 'G-F60LM558PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRkzoh6zK1fhC2g4YBJJxL6ialZntOQc',
    appId: '1:429185290860:android:e8a7f8e546276c3182fe49',
    messagingSenderId: '429185290860',
    projectId: 'onemusic-app',
    storageBucket: 'onemusic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJxPP2fmaKZoW3K9dYuKGlDXim_mMSF0s',
    appId: '1:429185290860:ios:06083528d6798c3f82fe49',
    messagingSenderId: '429185290860',
    projectId: 'onemusic-app',
    storageBucket: 'onemusic-app.firebasestorage.app',
    iosBundleId: 'com.onepersonai.onemusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJxPP2fmaKZoW3K9dYuKGlDXim_mMSF0s',
    appId: '1:429185290860:ios:06083528d6798c3f82fe49',
    messagingSenderId: '429185290860',
    projectId: 'onemusic-app',
    storageBucket: 'onemusic-app.firebasestorage.app',
    iosBundleId: 'com.onepersonai.onemusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcAuDI_4OyRbnp95-L9Z68WJ8cPskOnMo',
    appId: '1:429185290860:web:653e32e04f4a762f82fe49',
    messagingSenderId: '429185290860',
    projectId: 'onemusic-app',
    authDomain: 'onemusic-app.firebaseapp.com',
    storageBucket: 'onemusic-app.firebasestorage.app',
    measurementId: 'G-X2HG07L777',
  );
}
